version: 0.2

phases:
  build:
    commands:
      - ./gradlew test
      - ./gradlew assembleDebug
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app/build/outputs/apk/demo-haha-debug.apk